# 1. Array Creation:

In [2]:
import numpy as np

## a. Create a 1-dimensional array of integers from 1 to 10.

In [4]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## b. Create a 2-dimensional array with random float values of shape (3, 4).

In [16]:
# np.random.seed(42)  # for reproducing the same random value
b = np.random.rand(3,4)
b

array([[0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184]])

## c. Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [6]:
c = np.zeros((2,3,4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# 2. Array Operations:

## a. Given two 1-dimensional arrays, perform element-wise addition, subtraction, multiplication, and division.

In [10]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [11]:
addition = a+b
subtraction = a-b
multiplication = a*b
division = a/b

In [13]:
print(addition)
print(subtraction)
print(multiplication)
print(division)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


## b. Calculate the mean, median, and standard deviation of a given 1-dimensional array.

In [34]:
given_array = np.array([1,2,3,4,5])

mean = np.mean(given_array)   # given_array.mean() ni garna milxa kina vane mean() is a array method
median = np.median(given_array)
standard_deviation = np.std(given_array)  # given_array.mean() ni garna milxa kina vane std() is a array method

print(f"Mean is : {mean} \nMedian is : {median} \nStandard Deviation is : {standard_deviation}")

Mean is : 3.0 
Median is : 3.0 
Standard Deviation is : 1.4142135623730951


## c. Reshape a 1-dimensional array into a 2-dimensional array of shape (3,4).

In [17]:
given_array = np.random.randint(10,size=(2,6))
print(given_array)
given_array.reshape(3,4)

[[1 0 0 8 6 2]
 [9 7 2 1 9 5]]


array([[1, 0, 0, 8],
       [6, 2, 9, 7],
       [2, 1, 9, 5]], dtype=int32)

# 3. Array Indexing and Slicing:

## a. Extract the first row and last column of a 2-dimensional array.

In [41]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
a[0,:]

array([1, 2, 3, 4])

In [48]:
a[:,-1]

array([4, 8])

## b. Reverse the order of elements in a 1-dimensional array.

In [9]:
a = np.array([1,2,3,4,5])
a[::-1]

array([5, 4, 3, 2, 1])

## c. Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).

In [11]:
my_array = np.array([[1,2,3],[4,5,6]])
condition = my_array>2
my_array[condition]

array([3, 4, 5, 6])

# 4. Array Broadcasting:

## a. Add a scalar value to each element of a 2-dimensional array.

In [13]:
my_array = np.array([[1,2,3],[4,5,6]])
my_array+2

array([[3, 4, 5],
       [6, 7, 8]])

## b. Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.

In [16]:
oned_array = np.array([7,8,9])
twod_array = np.array([[1,2,3],[4,5,6]])
twod_array*oned_array

array([[ 7, 16, 27],
       [28, 40, 54]])

# 5. Linear Algebra:

## a. Calculate the dot product of two 1-dimensional arrays.

In [20]:
one = np.array([1,5,3])
two = np.array([4,5,6])
np.dot(one,two)

np.int64(47)

## b. Compute the matrix multiplication of two 2-dimensional arrays.

In [31]:
# one = np.array([[1,2],[5,6]])
# two = np.array([[6,1],[1,10]])
# np.matmul(one,two)

one = np.array([[1,2,3],[5,6,7]])
two = np.array([[6,7,1],[1,10,11],[1,2,3]])
np.matmul(one,two)

# number of columns in the first matrix must be equal to number of rows in the second matrix

array([[ 11,  33,  32],
       [ 43, 109,  92]])

## c. Find the inverse and determinant of a square matrix.

In [36]:
my_mat = np.array([[1,3],[4,5]])
inverse = np.linalg.inv(my_mat)
inverse

array([[-0.71428571,  0.42857143],
       [ 0.57142857, -0.14285714]])

In [37]:
determinant = np.linalg.det(my_mat)
determinant

np.float64(-6.999999999999999)

In [41]:
np.matmul(my_mat,inverse)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])